services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    networks: ['ollama']
    ports:
      - ${OPEN_WEBUI_PORT-3030}:8080
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'WEBUI_AUTH=false'
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks: ['ollama']
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama_storage:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ollama-pull-llama-gpu:
    image: ollama/ollama:latest
    networks: ['ollama']
    container_name: ollama-pull-llama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.1"
    depends_on:
      - ollama
networks:
  ollama:
volumes:
  ollama_storage:
  open-webui:
